os:
  - linux
  - osx
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install --ignore-scripts
script:
  - npm test
  - npm run devinstall
  - time git checkout
  - node ci-check

